Repository canada-ca/blogue-canada-ca-blog, pull requests merged in 2022-03, with the labels that each got.

#66 Create posts 2022-03-22
  en/_posts/2022-03-23-task-success.md
  en/images/thumbs/2022-03-23.png
  fr/_posts/2022-03-23-reussite-des-taches.md
  fr/images/thumbs/2022-03-23.png
Labels: documentation

#67 feat: Adding Open Graph support
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/metadata.html
Labels: enhancement

#68 Update 2022-03-23-reussite-des-taches.md
  fr/_posts/2022-03-23-reussite-des-taches.md
Labels: bug
