Repository canada-ca/blogue-canada-ca-blog, pull requests merged in 2022-04, with the labels that each got.

#69 Create posts 2022-04-01
  en/_posts/2022-04-01-new-design.md
  en/images/2022-04-01a.png
  en/images/2022-04-01b.png
  en/images/thumbs/2022-04-01.png
  fr/_posts/2022-04-01-nouvelle-conception.md
  fr/images/2022-04-01a.png
  fr/images/2022-04-01b.png
  fr/images/thumbs/2022-04-01.png
Labels: enhancement

#70 hotfix: Update 2022-04-01 posts
  en/_posts/2022-04-01-new-design.md
  fr/_posts/2022-04-01-nouvelle-conception.md
Labels: invalid

#71 fix: Update action url in `searchsite.html` and pages
  _includes/headers-includes/sitesearch.html
  en/pages/Canada.ca-spring-update.html
  en/pages/_drafts/project-overview-draft.html
  en/pages/_drafts/project-overview-draft3.html
  en/pages/project-overview.html
  en/pages/starting-a-business-decisions.html
  fr/pages/_drafts/apercu-projet-draft-plzrestart-need-toggles-from-latest-live.html
  fr/pages/_drafts/apercu-projet-draft.html
  fr/pages/apercu-projet.html
  fr/pages/decisions-demarrer-entreprise.html
Labels: bug
